version: '3.8'

services:
  # Nginx service
  nginx:
    image: nginx:latest
    container_name: nginx-container
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/html:/usr/share/nginx/html
    depends_on:
      - php
      - mysql

  # PHP service
  php:
    image: php:7.4-fpm
    container_name: php-container
    volumes:
      - ./php:/var/www/html
    depends_on:
      - mysql

  # MySQL service
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: lemp_database
      MYSQL_USER: lemp_user
      MYSQL_PASSWORD: lemp_password
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql

  # Additional services or configurations can be added as needed
